DROP DATABASE IF EXISTS db_appCI;
CREATE DATABASE db_appCI CHARACTER SET uf8;


CREATE TABLE usuarios(
	idusuario INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR (75) NOT NULL,
    email VARCHAR(75) NOT NULL,
    nick VARCHAR(75) NOT NULL,
    passwd VARCHAR(75) NOT NULL
);
